// ALL BLUE QA 체크리스트 정적 데이터 (자동 생성 - 385개 항목, 18개 카테고리)
// 실제 값(결과/비고/담당자/확인일자)은 Supabase의 qa_checklist_results 테이블에 item_id로 매핑되어 저장된다.
export interface QaChecklistItem {
  id: number;
  category: string;
  subFeature: string;
  item: string;
  priority: "상" | "중" | "하";
}

export const QA_CHECKLIST_ITEMS: QaChecklistItem[] = [
  { id: 1, category: "회원가입", subFeature: "공통", item: "이메일 형식 유효성 검사(잘못된 형식 입력 시 에러 표시)", priority: "상" },
  { id: 2, category: "회원가입", subFeature: "공통", item: "비밀번호 최소 길이/복잡도 규칙 검증", priority: "상" },
  { id: 3, category: "회원가입", subFeature: "공통", item: "비밀번호 확인란 불일치 시 에러 메시지", priority: "상" },
  { id: 4, category: "회원가입", subFeature: "공통", item: "이미 가입된 이메일로 재가입 시도 시 안내", priority: "중" },
  { id: 5, category: "회원가입", subFeature: "공통", item: "필수 약관(이용약관/개인정보처리방침) 미동의 시 가입 버튼 비활성화", priority: "중" },
  { id: 6, category: "회원가입", subFeature: "공통", item: "선택 약관 동의 여부가 정상적으로 저장되는지", priority: "중" },
  { id: 7, category: "회원가입", subFeature: "공통", item: "다이버 회원가입 - 닉네임/전화번호 등 필수 입력값 검증", priority: "상" },
  { id: 8, category: "회원가입", subFeature: "공통", item: "다이버 회원가입 완료 후 로그인 상태로 자동 전환되는지", priority: "중" },
  { id: 9, category: "회원가입", subFeature: "강사 가입", item: "강사 가입 시 자격증(라이선스) 파일 업로드 필수 검증", priority: "상" },
  { id: 10, category: "회원가입", subFeature: "강사 가입", item: "라이선스 업로드 시 이미지 미리보기 썸네일이 정상 표시되는지", priority: "중" },
  { id: 11, category: "회원가입", subFeature: "강사 가입", item: "지원하지 않는 파일 형식(예: exe) 업로드 시 거부되는지", priority: "중" },
  { id: 12, category: "회원가입", subFeature: "강사 가입", item: "파일 용량 제한 초과 시 에러 메시지", priority: "중" },
  { id: 13, category: "회원가입", subFeature: "강사 가입", item: "강사 서약서(PledgeAgreement) 내용 확인 후 서명(SignaturePad) 필수 처리", priority: "상" },
  { id: 14, category: "회원가입", subFeature: "강사 가입", item: "서명 없이 제출 시 제출 버튼 비활성화/에러", priority: "중" },
  { id: 15, category: "회원가입", subFeature: "강사 가입", item: "강사 가입 신청 후 관리자 승인 대기 상태로 전환되는지", priority: "중" },
  { id: 16, category: "회원가입", subFeature: "강사 가입", item: "관리자 승인 전까지 강사 기능(투어 생성 등) 접근이 제한되는지", priority: "중" },
  { id: 17, category: "회원가입", subFeature: "강사 가입", item: "OnboardingProgress 단계 표시가 실제 입력 진행 상황과 일치하는지", priority: "중" },
  { id: 18, category: "회원가입", subFeature: "강사 가입", item: "가입 중 뒤로가기/새로고침 시 입력값 유지 또는 안전한 초기화", priority: "중" },
  { id: 19, category: "회원가입", subFeature: "소셜 간편가입", item: "카카오 간편가입 버튼 클릭 시 OAuth 플로우 정상 진입", priority: "상" },
  { id: 20, category: "회원가입", subFeature: "소셜 간편가입", item: "네이버 간편가입 버튼 클릭 시 OAuth 플로우 정상 진입", priority: "상" },
  { id: 21, category: "회원가입", subFeature: "소셜 간편가입", item: "소셜 가입 시 이메일/닉네임 등 필수 정보가 정상 매핑되는지", priority: "상" },
  { id: 22, category: "회원가입", subFeature: "소셜 간편가입", item: "소셜 계정에 이미 연결된 이메일로 일반 가입 시도 시 충돌 처리", priority: "상" },
  { id: 23, category: "회원가입", subFeature: "소셜 간편가입", item: "소셜 로그인 취소/거부 시 에러 없이 가입 화면으로 복귀", priority: "상" },
  { id: 24, category: "회원가입", subFeature: "소셜 간편가입", item: "소셜 가입도 다이버/강사 역할 선택 플로우를 동일하게 거치는지", priority: "상" },
  { id: 25, category: "회원가입", subFeature: "역할 분기", item: "다이버/강사 역할 선택에 따라 이후 입력 폼이 올바르게 분기되는지", priority: "상" },
  { id: 26, category: "회원가입", subFeature: "역할 분기", item: "가입 완료 후 역할(RoleContext)이 정확히 반영되어 하단 네비게이션이 다르게 보이는지", priority: "상" },
  { id: 27, category: "로그인/계정", subFeature: "로그인", item: "올바른 이메일/비밀번호 로그인 성공", priority: "상" },
  { id: 28, category: "로그인/계정", subFeature: "로그인", item: "잘못된 비밀번호 입력 시 에러 메시지", priority: "상" },
  { id: 29, category: "로그인/계정", subFeature: "로그인", item: "존재하지 않는 이메일 로그인 시도 시 에러 메시지", priority: "상" },
  { id: 30, category: "로그인/계정", subFeature: "로그인", item: "로그인 실패 다회 시도 시 잠금/제한 정책 여부 확인", priority: "상" },
  { id: 31, category: "로그인/계정", subFeature: "로그인", item: "로그인 유지(세션 지속) 기능 동작 확인", priority: "상" },
  { id: 32, category: "로그인/계정", subFeature: "로그인", item: "역할(다이버/강사/관리자)에 따라 로그인 후 리다이렉트 경로가 올바른지", priority: "상" },
  { id: 33, category: "로그인/계정", subFeature: "비밀번호 재설정", item: "ResetPassword 페이지에서 이메일 입력 후 재설정 메일 발송", priority: "상" },
  { id: 34, category: "로그인/계정", subFeature: "비밀번호 재설정", item: "재설정 링크 만료 후 접근 시 에러 처리", priority: "상" },
  { id: 35, category: "로그인/계정", subFeature: "비밀번호 재설정", item: "새 비밀번호 설정 후 기존 비밀번호로 로그인 불가 확인", priority: "상" },
  { id: 36, category: "로그인/계정", subFeature: "비밀번호 재설정", item: "새 비밀번호 설정 후 신규 비밀번호로 정상 로그인", priority: "상" },
  { id: 37, category: "로그인/계정", subFeature: "권한 제어", item: "RequireRole 가드 - 다이버 계정으로 /instructor 경로 접근 시 차단", priority: "상" },
  { id: 38, category: "로그인/계정", subFeature: "권한 제어", item: "RequireRole 가드 - 일반 계정으로 /admin 경로 접근 시 차단", priority: "상" },
  { id: 39, category: "로그인/계정", subFeature: "권한 제어", item: "미승인 강사 계정으로 강사 전용 기능 접근 시 안내 문구 노출", priority: "중" },
  { id: 40, category: "로그인/계정", subFeature: "권한 제어", item: "패널티(경고) 누적으로 제재된 강사 계정 로그인/기능 제한 여부", priority: "중" },
  { id: 41, category: "로그인/계정", subFeature: "권한 제어", item: "로그아웃 시 세션/토큰이 완전히 삭제되는지", priority: "중" },
  { id: 42, category: "로그인/계정", subFeature: "권한 제어", item: "로그아웃 후 뒤로가기로 인증 필요 페이지 재진입 시 로그인 화면으로 리다이렉트", priority: "중" },
  { id: 43, category: "로그인/계정", subFeature: "권한 제어", item: "다중 탭에서 로그아웃 시 다른 탭도 세션 만료 반영되는지", priority: "중" },
  { id: 44, category: "로그인/계정", subFeature: "권한 제어", item: "Supabase 세션 만료 시 자동 재로그인 유도 처리", priority: "중" },
  { id: 45, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "투어명/지역/국가 등 필수 항목 미입력 시 저장 차단", priority: "상" },
  { id: 46, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "투어 카테고리(스쿠버다이빙/프리다이빙) 선택 필수 검증", priority: "상" },
  { id: 47, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "투어 태그(TOUR_TAG_OPTIONS) 프리셋 선택 및 커스텀 태그 추가/삭제 동작", priority: "상" },
  { id: 48, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "출발일/종료일 날짜 유효성(종료일이 시작일보다 빠른 경우 차단)", priority: "상" },
  { id: 49, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "모집 정원 숫자 입력 검증(0 이하 입력 차단)", priority: "상" },
  { id: 50, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "모집 마감일이 출발일 이후로 설정되는 경우 에러 처리", priority: "상" },
  { id: 51, category: "투어 생성/관리(강사)", subFeature: "기본 정보 입력", item: "가격 입력 시 숫자 이외 문자 입력 차단", priority: "상" },
  { id: 52, category: "투어 생성/관리(강사)", subFeature: "이미지/미디어", item: "메인 사진 업로드 시 썸네일 미리보기 정상 표시(FileDropzone)", priority: "상" },
  { id: 53, category: "투어 생성/관리(강사)", subFeature: "이미지/미디어", item: "다이브 사이트 갤러리 다중 이미지 업로드 및 각 파일 미리보기 확인", priority: "중" },
  { id: 54, category: "투어 생성/관리(강사)", subFeature: "이미지/미디어", item: "이미지가 아닌 파일 업로드 시 기존 파일 아이콘으로 정상 폴백되는지", priority: "중" },
  { id: 55, category: "투어 생성/관리(강사)", subFeature: "이미지/미디어", item: "업로드한 이미지 개별 삭제 시 미리보기 목록에서도 제거되는지", priority: "중" },
  { id: 56, category: "투어 생성/관리(강사)", subFeature: "이미지/미디어", item: "이미지 미리보기 URL이 컴포넌트 언마운트/재선택 시 메모리 누수 없이 해제되는지", priority: "중" },
  { id: 57, category: "투어 생성/관리(강사)", subFeature: "이미지/미디어", item: "대용량 이미지 업로드 시 리사이즈/용량 제한 처리", priority: "중" },
  { id: 58, category: "투어 생성/관리(강사)", subFeature: "항공편 정보", item: "강사 항공편 정보(TourFlightInfoCard) 입력 필드 저장/조회", priority: "중" },
  { id: 59, category: "투어 생성/관리(강사)", subFeature: "항공편 정보", item: "항공편 정보 미입력 시 카드가 빈 상태로 정상 노출되는지", priority: "중" },
  { id: 60, category: "투어 생성/관리(강사)", subFeature: "항공편 정보", item: "항공편 정보 라벨이 '강사 항공편 정보'로 정확히 표시되는지", priority: "중" },
  { id: 61, category: "투어 생성/관리(강사)", subFeature: "센터/장소 정보", item: "이용 센터(TourCenterCard/DiveCenterCard) 정보 입력 및 표시", priority: "중" },
  { id: 62, category: "투어 생성/관리(강사)", subFeature: "센터/장소 정보", item: "센터 편의시설(전용 보트, Nitrox 등) 태그 선택 반영", priority: "중" },
  { id: 63, category: "투어 생성/관리(강사)", subFeature: "센터/장소 정보", item: "위치 지도 미리보기 '준비 중' 플레이스홀더 노출 확인", priority: "중" },
  { id: 64, category: "투어 생성/관리(강사)", subFeature: "센터/장소 정보", item: "포함/불포함 사항(InclusionsExclusionsCard) 리스트 추가/삭제", priority: "중" },
  { id: 65, category: "투어 생성/관리(강사)", subFeature: "센터/장소 정보", item: "강사 추천 준비물/필독 사항 텍스트 저장 및 표시", priority: "중" },
  { id: 66, category: "투어 생성/관리(강사)", subFeature: "서약/정책", item: "투어 등록 시 TourPledgeAgreement 서약 없이 등록 불가", priority: "상" },
  { id: 67, category: "투어 생성/관리(강사)", subFeature: "서약/정책", item: "다이버 위반 사항 및 제재 정책 문구가 투어 상세에 정확히 노출되는지", priority: "중" },
  { id: 68, category: "투어 생성/관리(강사)", subFeature: "서약/정책", item: "강사 위반 사항 및 제재 정책 문구가 투어 상세에 정확히 노출되는지", priority: "중" },
  { id: 69, category: "투어 생성/관리(강사)", subFeature: "수정/삭제", item: "TourEditPage에서 기존 등록 투어 수정 후 저장 반영", priority: "상" },
  { id: 70, category: "투어 생성/관리(강사)", subFeature: "수정/삭제", item: "예약이 이미 있는 투어의 정원을 예약 인원 미만으로 축소 시 차단", priority: "상" },
  { id: 71, category: "투어 생성/관리(강사)", subFeature: "수정/삭제", item: "투어 삭제(또는 마감 처리) 시 이미 예약한 다이버에게 미치는 영향 확인", priority: "상" },
  { id: 72, category: "투어 생성/관리(강사)", subFeature: "수정/삭제", item: "투어 상태(모집중/마감/취소) 전환이 검색결과/상세페이지에 즉시 반영되는지", priority: "상" },
  { id: 73, category: "투어 생성/관리(강사)", subFeature: "수정/삭제", item: "관리자 승인 대기(adminStatus) 투어가 검색결과에 노출되지 않는지", priority: "상" },
  { id: 74, category: "투어 생성/관리(강사)", subFeature: "노출/검색 연동", item: "새로 등록한 투어가 검색 결과 목록에 정상 노출되는지", priority: "중" },
  { id: 75, category: "투어 생성/관리(강사)", subFeature: "노출/검색 연동", item: "투어 카드에 강사 경력/로그(예: 12년/2,100+) 형식이 올바르게 표시되는지", priority: "중" },
  { id: 76, category: "투어 생성/관리(강사)", subFeature: "노출/검색 연동", item: "투어 카드에 진행 투어 횟수가 정확히 집계되어 표시되는지", priority: "중" },
  { id: 77, category: "투어 생성/관리(강사)", subFeature: "노출/검색 연동", item: "동일 강사의 여러 투어 등록 시 각 투어별 진행 투어 카운트가 올바른지", priority: "중" },
  { id: 78, category: "투어 생성/관리(강사)", subFeature: "리마인드/알림", item: "투어 등록 완료 후 강사에게 확인 알림/토스트 노출", priority: "상" },
  { id: 79, category: "투어 생성/관리(강사)", subFeature: "리마인드/알림", item: "모집 마감 임박 투어에 대한 강사 알림", priority: "상" },
  { id: 80, category: "투어 생성/관리(강사)", subFeature: "리마인드/알림", item: "정원 미달로 인한 진행 여부 결정(UnderMinDecisionPanel) 플로우 동작", priority: "상" },
  { id: 81, category: "투어 생성/관리(강사)", subFeature: "리마인드/알림", item: "강사가 최소 인원 미달 투어를 취소/강행 결정 시 관련 데이터가 DB에 정확히 반영되는지", priority: "상" },
  { id: 82, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "여행지/국가 검색 필터 동작", priority: "상" },
  { id: 83, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "출발 월 복수 선택 필터 동작", priority: "중" },
  { id: 84, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "카테고리(스쿠버다이빙/프리다이빙) 필터 동작", priority: "중" },
  { id: 85, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "검색 결과 없음 상태 UI 노출", priority: "중" },
  { id: 86, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "정렬(가격순/평점순 등 존재 시) 기능 동작", priority: "중" },
  { id: 87, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "모집중인 투어 개수 카운트가 실제 목록과 일치하는지", priority: "중" },
  { id: 88, category: "투어 탐색/상세(소비자)", subFeature: "홈/검색", item: "페이지네이션 또는 무한스크롤 동작(대량 데이터 기준)", priority: "중" },
  { id: 89, category: "투어 탐색/상세(소비자)", subFeature: "투어 상세", item: "투어 소개 박스가 항공편 정보 카드와 동일한 테두리 스타일로 표시되는지", priority: "중" },
  { id: 90, category: "투어 탐색/상세(소비자)", subFeature: "투어 상세", item: "투어 갤러리 이미지 슬라이드/썸네일 클릭 전환 동작", priority: "중" },
  { id: 91, category: "투어 탐색/상세(소비자)", subFeature: "투어 상세", item: "모집 마감일이 지난 투어 상세 접근 시 '마감' 상태 노출", priority: "중" },
  { id: 92, category: "투어 탐색/상세(소비자)", subFeature: "투어 상세", item: "정원이 가득 찬 투어의 '예약하기' 버튼 비활성화 및 안내 문구", priority: "중" },
  { id: 93, category: "투어 탐색/상세(소비자)", subFeature: "투어 상세", item: "가격 표시 형식(천단위 콤마, '~' 표기) 정확성", priority: "중" },
  { id: 94, category: "투어 탐색/상세(소비자)", subFeature: "강사 신뢰 카드", item: "InstructorTrustCard에 안전 패널티 항목이 노출되지 않고 '진행 투어'로 대체되어 있는지", priority: "상" },
  { id: 95, category: "투어 탐색/상세(소비자)", subFeature: "강사 신뢰 카드", item: "플랫폼 인증강사 배지 노출 조건 확인(인증되지 않은 강사는 배지 미노출)", priority: "상" },
  { id: 96, category: "투어 탐색/상세(소비자)", subFeature: "강사 신뢰 카드", item: "강사 찜하기(북마크) 아이콘 클릭 시 상태 토글 및 저장", priority: "상" },
  { id: 97, category: "투어 탐색/상세(소비자)", subFeature: "강사 신뢰 카드", item: "강사 프로필 더보기 클릭 시 InstructorPublicProfile로 정상 이동", priority: "상" },
  { id: 98, category: "투어 탐색/상세(소비자)", subFeature: "강사 신뢰 카드", item: "경력/로그, 완료율, 진행 투어 3개 지표 값이 실제 데이터와 일치하는지", priority: "상" },
  { id: 99, category: "투어 탐색/상세(소비자)", subFeature: "후기 및 평점", item: "후기 및 평점 섹션이 박스 스타일로 감싸져 표시되는지", priority: "중" },
  { id: 100, category: "투어 탐색/상세(소비자)", subFeature: "후기 및 평점", item: "후기가 없는 투어의 '아직 등록된 후기가 없습니다' 문구 노출", priority: "중" },
  { id: 101, category: "투어 탐색/상세(소비자)", subFeature: "후기 및 평점", item: "후기 목록의 별점 평균이 개별 후기 점수와 일치하는지", priority: "중" },
  { id: 102, category: "투어 탐색/상세(소비자)", subFeature: "후기 및 평점", item: "카테고리별 별점(CategoryStarRow) 세부 항목이 정확히 집계되는지", priority: "중" },
  { id: 103, category: "투어 탐색/상세(소비자)", subFeature: "후기 및 평점", item: "후기 사진 첨부 표시 및 확대 보기 동작", priority: "중" },
  { id: 104, category: "투어 탐색/상세(소비자)", subFeature: "예약 불가 처리", item: "adminStatus가 있거나 status가 closed인 투어는 예약하기 버튼이 비활성화되는지", priority: "상" },
  { id: 105, category: "투어 탐색/상세(소비자)", subFeature: "예약 불가 처리", item: "예약 불가 투어를 위시리스트에 추가 시도 시 차단 및 안내 토스트", priority: "상" },
  { id: 106, category: "투어 탐색/상세(소비자)", subFeature: "예약 불가 처리", item: "이미 위시리스트에 있던 투어가 이후 예약 불가 상태로 전환되면 위시리스트에서 자동 제외되는지", priority: "상" },
  { id: 107, category: "예약", subFeature: "예약 생성", item: "인원 수 선택이 잔여 정원을 초과하지 못하도록 제한", priority: "상" },
  { id: 108, category: "예약", subFeature: "예약 생성", item: "옵션(TourOptionsSelector) 선택에 따라 총 금액이 정확히 재계산되는지", priority: "상" },
  { id: 109, category: "예약", subFeature: "예약 생성", item: "예약 진행 중 이탈(뒤로가기) 시 임시 예약이 남지 않는지", priority: "상" },
  { id: 110, category: "예약", subFeature: "예약 생성", item: "동시에 여러 사용자가 마지막 잔여 좌석에 예약 시도 시 정원 초과 방지", priority: "상" },
  { id: 111, category: "예약", subFeature: "예약 생성", item: "예약 완료 후 정원(모집 인원) 카운트가 즉시 갱신되는지", priority: "상" },
  { id: 112, category: "예약", subFeature: "예약 내역", item: "MyBookings/BookingHistoryList에서 예약 상태(대기/확정/완료/취소)가 정확히 구분 표시되는지", priority: "상" },
  { id: 113, category: "예약", subFeature: "예약 내역", item: "예약 상세에서 투어 정보/강사 정보/결제 금액이 실제 예약 데이터와 일치하는지", priority: "중" },
  { id: 114, category: "예약", subFeature: "예약 내역", item: "과거 완료된 투어에 대해 후기 작성 버튼이 노출되는지", priority: "중" },
  { id: 115, category: "예약", subFeature: "예약 내역", item: "이미 후기를 작성한 예약에 대해 중복 작성 버튼이 비활성화되는지", priority: "중" },
  { id: 116, category: "예약", subFeature: "예약 내역", item: "예약 내역이 최신순으로 정렬되는지", priority: "중" },
  { id: 117, category: "예약", subFeature: "캘린더 연동", item: "CalendarSyncButtons를 통한 구글/애플 캘린더 등록 링크 정확성", priority: "하" },
  { id: 118, category: "예약", subFeature: "캘린더 연동", item: "캘린더 등록 시 투어 일정/장소 정보가 올바르게 채워지는지", priority: "하" },
  { id: 119, category: "예약", subFeature: "정원/최소인원", item: "최소 출발 인원 미달 시 강사의 진행/취소 결정 이후 다이버에게 결과가 정확히 통보되는지", priority: "상" },
  { id: 120, category: "예약", subFeature: "정원/최소인원", item: "최소인원 미달로 취소 결정 시 전액 환불이 자동 처리되는지", priority: "상" },
  { id: 121, category: "예약", subFeature: "정원/최소인원", item: "최소인원 미달로 강행 결정 시 예약이 정상 확정 상태로 전환되는지", priority: "상" },
  { id: 122, category: "예약", subFeature: "그룹채팅", item: "예약 확정 시 해당 투어 그룹채팅방에 자동 초대되는지", priority: "중" },
  { id: 123, category: "예약", subFeature: "그룹채팅", item: "채팅방에서 강사/다이버 메시지 송수신 정상 동작", priority: "중" },
  { id: 124, category: "예약", subFeature: "그룹채팅", item: "예약 취소 시 그룹채팅방 접근 권한이 제거되는지", priority: "중" },
  { id: 125, category: "예약", subFeature: "1인 예약/다인 예약", item: "1인 예약과 다인 예약(동반자 정보 포함) 입력 폼 분기 확인", priority: "중" },
  { id: 126, category: "예약", subFeature: "1인 예약/다인 예약", item: "동반자 정보(이름/자격증 등) 필수 입력 검증", priority: "중" },
  { id: 127, category: "예약", subFeature: "예외 처리", item: "네트워크 오류 발생 시 예약 요청이 중복 전송되지 않는지", priority: "상" },
  { id: 128, category: "예약", subFeature: "예외 처리", item: "결제 대기 중 세션 만료 시 예약이 중복 생성되지 않는지", priority: "상" },
  { id: 129, category: "예약", subFeature: "예외 처리", item: "예약 완료 후 동일 투어 재예약(중복 예약) 허용 정책 확인", priority: "상" },
  { id: 130, category: "결제", subFeature: "결제 수단", item: "TossPaymentWidget 카드 결제 정상 동작(테스트 카드 기준)", priority: "상" },
  { id: 131, category: "결제", subFeature: "결제 수단", item: "간편결제(카카오페이/네이버페이 등) 연동 시 정상 리다이렉트", priority: "상" },
  { id: 132, category: "결제", subFeature: "결제 수단", item: "결제 수단 미선택 상태에서 결제 버튼 비활성화", priority: "상" },
  { id: 133, category: "결제", subFeature: "결제 프로세스", item: "결제 금액이 예약 옵션/인원수 기준 계산과 정확히 일치하는지", priority: "상" },
  { id: 134, category: "결제", subFeature: "결제 프로세스", item: "쿠폰/할인 적용 시 최종 결제 금액이 올바르게 차감되는지", priority: "상" },
  { id: 135, category: "결제", subFeature: "결제 프로세스", item: "PaymentReceiptBreakdown 영수증 항목(투어 금액/수수료/할인)이 합계와 일치하는지", priority: "상" },
  { id: 136, category: "결제", subFeature: "결제 프로세스", item: "결제 성공 시 PaymentSuccess 페이지로 이동 및 예약 상태 '확정' 반영", priority: "상" },
  { id: 137, category: "결제", subFeature: "결제 프로세스", item: "결제 실패 시 PaymentFail 페이지로 이동 및 재시도 유도", priority: "상" },
  { id: 138, category: "결제", subFeature: "결제 프로세스", item: "결제 진행 중 브라우저 종료/새로고침 시 결제 상태 정합성 확인", priority: "상" },
  { id: 139, category: "결제", subFeature: "결제 프로세스", item: "결제 완료 후 동일 예약 재결제 시도 차단", priority: "상" },
  { id: 140, category: "결제", subFeature: "실결제 연동(현재 Mock 여부 점검)", item: "Checkout.tsx의 결제 모의(mock) 우회 로직이 실서비스 배포 전 제거되었는지", priority: "상" },
  { id: 141, category: "결제", subFeature: "실결제 연동(현재 Mock 여부 점검)", item: "verify-payment Supabase Edge Function이 실제 배포/활성화되어 있는지", priority: "상" },
  { id: 142, category: "결제", subFeature: "실결제 연동(현재 Mock 여부 점검)", item: "결제 검증(verify-payment)이 서버측에서 금액 위변조를 탐지하는지", priority: "상" },
  { id: 143, category: "결제", subFeature: "실결제 연동(현재 Mock 여부 점검)", item: "웹훅/콜백 실패 시 재시도 또는 수동 확인 프로세스 존재 여부", priority: "상" },
  { id: 144, category: "결제", subFeature: "정산(강사)", item: "SettlementLedger에 결제 완료 건이 정확한 금액/수수료로 집계되는지", priority: "상" },
  { id: 145, category: "결제", subFeature: "정산(강사)", item: "SettlementDetailCard 상세 내역이 실제 예약/결제 데이터와 일치하는지", priority: "상" },
  { id: 146, category: "결제", subFeature: "정산(강사)", item: "정산 주기(월별/투어 완료 후 등)에 따라 정산 대상이 올바르게 필터링되는지", priority: "상" },
  { id: 147, category: "결제", subFeature: "정산(강사)", item: "환불이 발생한 예약이 정산 금액에서 올바르게 제외/차감되는지", priority: "상" },
  { id: 148, category: "결제", subFeature: "쿠폰/프로모션", item: "AdminCouponsPage에서 발급한 쿠폰이 결제 화면에서 정상 적용되는지", priority: "중" },
  { id: 149, category: "결제", subFeature: "쿠폰/프로모션", item: "쿠폰 사용 기한 만료 시 적용 차단", priority: "중" },
  { id: 150, category: "결제", subFeature: "쿠폰/프로모션", item: "쿠폰 최소 결제 금액 조건 미충족 시 적용 차단", priority: "중" },
  { id: 151, category: "결제", subFeature: "쿠폰/프로모션", item: "1회용 쿠폰의 중복 사용 방지", priority: "중" },
  { id: 152, category: "결제", subFeature: "영수증/증빙", item: "결제 영수증(현금영수증/세금계산서 등) 발급 요청 플로우", priority: "하" },
  { id: 153, category: "결제", subFeature: "영수증/증빙", item: "영수증 재발급 또는 다운로드 기능 동작", priority: "하" },
  { id: 154, category: "결제", subFeature: "영수증/증빙", item: "환불 발생 시 영수증에 환불 내역이 반영되는지", priority: "하" },
  { id: 155, category: "취소/환불", subFeature: "환불 정책 로직", item: "30일 이상 남은 취소 시 100% 환불 계산 확인", priority: "상" },
  { id: 156, category: "취소/환불", subFeature: "환불 정책 로직", item: "15~29일 남은 취소 시 50% 환불 계산 확인", priority: "상" },
  { id: 157, category: "취소/환불", subFeature: "환불 정책 로직", item: "7~14일 남은 취소 시 30% 환불 계산 확인", priority: "상" },
  { id: 158, category: "취소/환불", subFeature: "환불 정책 로직", item: "7일 미만 남은 취소 시 0% 환불 계산 확인(과거 isConfirmed 예외로 100% 되던 버그 재발 여부 회귀 테스트)", priority: "상" },
  { id: 159, category: "취소/환불", subFeature: "환불 정책 로직", item: "환불율 계산이 취소 시점의 남은 일수를 정확히 기준으로 하는지(캐시된 값 사용 금지)", priority: "상" },
  { id: 160, category: "취소/환불", subFeature: "취소 사유별 분기", item: "개인 사유 취소 시 위 일자 기준 환불 정책이 정상 적용되는지", priority: "상" },
  { id: 161, category: "취소/환불", subFeature: "취소 사유별 분기", item: "강사/플랫폼 귀책(불가항력) 취소 시 전액 환불 처리되는지", priority: "상" },
  { id: 162, category: "취소/환불", subFeature: "취소 사유별 분기", item: "CancellationRefundPolicyCard에 표시되는 예상 환불액이 실제 처리 금액과 일치하는지", priority: "중" },
  { id: 163, category: "취소/환불", subFeature: "취소 사유별 분기", item: "취소 사유 입력 없이 취소 신청 시 필수 입력 검증", priority: "중" },
  { id: 164, category: "취소/환불", subFeature: "취소 신청/처리", item: "CancelBookingDialog에서 취소 확인 절차(2단계 확인 등) 동작", priority: "상" },
  { id: 165, category: "취소/환불", subFeature: "취소 신청/처리", item: "취소 신청 후 예약 상태가 즉시 '취소 처리중' 또는 '취소완료'로 반영되는지", priority: "상" },
  { id: 166, category: "취소/환불", subFeature: "취소 신청/처리", item: "관리자 CancellationReviewQueue에서 취소 승인/반려 처리 동작", priority: "상" },
  { id: 167, category: "취소/환불", subFeature: "취소 신청/처리", item: "취소 반려 시 예약자에게 사유가 정확히 전달되는지", priority: "상" },
  { id: 168, category: "취소/환불", subFeature: "취소 신청/처리", item: "환불 처리 완료까지 걸리는 시간/상태 표시(진행중/완료) 정확성", priority: "상" },
  { id: 169, category: "취소/환불", subFeature: "분쟁조정", item: "InstructorArbitrationRoom과 AdminArbitrationRoom 간 메시지/증빙이 동기화되는지", priority: "중" },
  { id: 170, category: "취소/환불", subFeature: "분쟁조정", item: "분쟁조정 신청 시 관련 예약/취소 데이터가 자동 첨부되는지", priority: "중" },
  { id: 171, category: "취소/환불", subFeature: "분쟁조정", item: "분쟁조정 결과에 따라 환불 비율이 재조정되는지", priority: "중" },
  { id: 172, category: "취소/환불", subFeature: "안전 패널티", item: "관리자 경고 부여 시 입력한 패널티 사유가 DB에 저장되는지", priority: "상" },
  { id: 173, category: "취소/환불", subFeature: "안전 패널티", item: "패널티 사유가 검색 카드/투어 카드에는 노출되지 않고 강사 프로필 상세에서만 노출되는지", priority: "상" },
  { id: 174, category: "취소/환불", subFeature: "안전 패널티", item: "패널티 누적 0회인 강사는 패널티 카드 자체가 노출되지 않는지", priority: "상" },
  { id: 175, category: "취소/환불", subFeature: "안전 패널티", item: "패널티 사유 미입력 상태(기존 데이터)에서 '사유가 등록되지 않았습니다' 문구 노출", priority: "상" },
  { id: 176, category: "취소/환불", subFeature: "안전 패널티", item: "패널티 누적 횟수가 일정 기준 초과 시 계정 제재(로그인 제한 등)로 이어지는지", priority: "상" },
  { id: 177, category: "취소/환불", subFeature: "회귀 테스트", item: "6일 남은 예약 취소 시 0% 환불이 정확히 적용되는지(재현 시나리오 재검증)", priority: "상" },
  { id: 178, category: "취소/환불", subFeature: "회귀 테스트", item: "20일 남은 예약 취소 시 50% 환불 적용 확인", priority: "상" },
  { id: 179, category: "취소/환불", subFeature: "회귀 테스트", item: "35일 남은 예약 취소 시 100% 환불 적용 확인", priority: "상" },
  { id: 180, category: "위시리스트/찜하기", subFeature: "투어 찜", item: "찜 아이콘 클릭 시 위시리스트에 즉시 추가/제거되는지(낙관적 업데이트)", priority: "중" },
  { id: 181, category: "위시리스트/찜하기", subFeature: "투어 찜", item: "위시리스트 목록에서 예약 불가 투어가 자동으로 숨김/제외되는지", priority: "중" },
  { id: 182, category: "위시리스트/찜하기", subFeature: "투어 찜", item: "이미 찜한 예약 불가 투어는 목록에서 사라지되 취소(제거)는 가능한지", priority: "중" },
  { id: 183, category: "위시리스트/찜하기", subFeature: "투어 찜", item: "로그인하지 않은 사용자가 찜 시도 시 로그인 유도", priority: "중" },
  { id: 184, category: "위시리스트/찜하기", subFeature: "투어 찜", item: "찜한 투어 개수가 마이페이지 등에서 정확히 카운트되는지", priority: "중" },
  { id: 185, category: "위시리스트/찜하기", subFeature: "강사 찜(팔로우)", item: "홈/검색 투어 카드에서 강사 찜하기 버튼 동작", priority: "중" },
  { id: 186, category: "위시리스트/찜하기", subFeature: "강사 찜(팔로우)", item: "투어 상세의 강사 신뢰 카드에서 강사 찜하기 버튼 동작", priority: "중" },
  { id: 187, category: "위시리스트/찜하기", subFeature: "강사 찜(팔로우)", item: "동일 강사를 여러 화면에서 찜해도 상태가 일관되게 동기화되는지", priority: "중" },
  { id: 188, category: "위시리스트/찜하기", subFeature: "강사 찜(팔로우)", item: "강사 찜 취소 시 관련 알림 구독도 해제되는지", priority: "중" },
  { id: 189, category: "위시리스트/찜하기", subFeature: "강사 찜(팔로우)", item: "강사 찜 목록이 별도 화면(찜한 강사 목록)에서 조회 가능한지", priority: "중" },
  { id: 190, category: "위시리스트/찜하기", subFeature: "동기화", item: "여러 기기/브라우저에서 로그인 시 위시리스트가 동일하게 동기화되는지", priority: "하" },
  { id: 191, category: "위시리스트/찜하기", subFeature: "동기화", item: "위시리스트 데이터가 새로고침 후에도 유지되는지", priority: "하" },
  { id: 192, category: "위시리스트/찜하기", subFeature: "동기화", item: "탈퇴/계정 삭제 시 위시리스트 데이터가 함께 정리되는지", priority: "하" },
  { id: 193, category: "후기/평점", subFeature: "작성", item: "완료된 예약에 대해서만 후기 작성 가능한지", priority: "상" },
  { id: 194, category: "후기/평점", subFeature: "작성", item: "후기 작성 시 별점(전체/카테고리별)이 필수 입력인지", priority: "중" },
  { id: 195, category: "후기/평점", subFeature: "작성", item: "후기 텍스트 최소/최대 글자수 제한", priority: "중" },
  { id: 196, category: "후기/평점", subFeature: "작성", item: "후기 사진 첨부 개수 제한 및 업로드 미리보기", priority: "중" },
  { id: 197, category: "후기/평점", subFeature: "작성", item: "동일 예약에 대한 중복 후기 작성 차단", priority: "중" },
  { id: 198, category: "후기/평점", subFeature: "노출", item: "작성한 후기가 투어 상세 후기 섹션에 즉시 반영되는지", priority: "중" },
  { id: 199, category: "후기/평점", subFeature: "노출", item: "후기 평균 별점이 투어 카드/검색 결과에도 정확히 반영되는지", priority: "중" },
  { id: 200, category: "후기/평점", subFeature: "노출", item: "부적절한 후기 신고 기능 동작", priority: "중" },
  { id: 201, category: "후기/평점", subFeature: "관리자 모니터링", item: "ReviewModerationQueue에서 신고된 후기 검토/삭제 처리", priority: "상" },
  { id: 202, category: "후기/평점", subFeature: "관리자 모니터링", item: "삭제된 후기가 투어 상세/평점 평균 계산에서 즉시 제외되는지", priority: "중" },
  { id: 203, category: "후기/평점", subFeature: "관리자 모니터링", item: "욕설/스팸 필터링(있을 경우) 동작 확인", priority: "중" },
  { id: 204, category: "강사 브랜드 페이지/프로필", subFeature: "히어로/기본 정보", item: "경력/자격/소속 등 라이선스 라인이 정확히 표시되는지", priority: "중" },
  { id: 205, category: "강사 브랜드 페이지/프로필", subFeature: "히어로/기본 정보", item: "총 로그수/투어 수/경력 연차 인라인 정보 표시 정확성", priority: "중" },
  { id: 206, category: "강사 브랜드 페이지/프로필", subFeature: "히어로/기본 정보", item: "전문 분야 태그(specialtyTags) 등록 및 프로필에 정확히 노출되는지", priority: "중" },
  { id: 207, category: "강사 브랜드 페이지/프로필", subFeature: "히어로/기본 정보", item: "사용 언어 태그 등록 및 노출 확인", priority: "중" },
  { id: 208, category: "강사 브랜드 페이지/프로필", subFeature: "히어로/기본 정보", item: "교육 철학/좋아하는 다이빙 텍스트 저장 및 표시", priority: "중" },
  { id: 209, category: "강사 브랜드 페이지/프로필", subFeature: "SNS/연락", item: "인스타그램/유튜브/페이스북/블로그/홈페이지 링크 등록 시 아이콘 노출", priority: "중" },
  { id: 210, category: "강사 브랜드 페이지/프로필", subFeature: "SNS/연락", item: "SNS 링크 미등록 시 해당 아이콘 행 자체가 숨겨지는지", priority: "하" },
  { id: 211, category: "강사 브랜드 페이지/프로필", subFeature: "SNS/연락", item: "SNS 링크 클릭 시 새 탭으로 안전하게 이동하는지(rel=noopener 등)", priority: "하" },
  { id: 212, category: "강사 브랜드 페이지/프로필", subFeature: "통계/지표", item: "재예약률(rebookingRate) 계산이 실제 반복 예약 다이버 비율과 일치하는지", priority: "상" },
  { id: 213, category: "강사 브랜드 페이지/프로필", subFeature: "통계/지표", item: "투어 완료율 지표 계산 정확성", priority: "중" },
  { id: 214, category: "강사 브랜드 페이지/프로필", subFeature: "통계/지표", item: "진행 투어/총 로그수 지표가 실시간 데이터와 일치하는지", priority: "중" },
  { id: 215, category: "강사 브랜드 페이지/프로필", subFeature: "갤러리", item: "갤러리 이미지가 강사의 투어 메인/갤러리 사진과 후기 사진에서 정확히 취합되는지", priority: "중" },
  { id: 216, category: "강사 브랜드 페이지/프로필", subFeature: "갤러리", item: "갤러리 이미지 클릭 시 라이트박스(Dialog) 확대 보기 동작", priority: "중" },
  { id: 217, category: "강사 브랜드 페이지/프로필", subFeature: "갤러리", item: "갤러리 이미지 30장 초과 시 최신순 정렬 및 개수 제한 확인", priority: "중" },
  { id: 218, category: "강사 브랜드 페이지/프로필", subFeature: "갤러리", item: "중복 이미지가 갤러리에 중복 노출되지 않는지(dedup 확인)", priority: "중" },
  { id: 219, category: "강사 브랜드 페이지/프로필", subFeature: "패널티(공개 프로필)", item: "안전 패널티 누적 횟수와 사유가 강사 프로필 더보기 화면에서만 노출되는지", priority: "상" },
  { id: 220, category: "강사 브랜드 페이지/프로필", subFeature: "패널티(공개 프로필)", item: "패널티 0회인 강사는 해당 섹션이 표시되지 않는지", priority: "상" },
  { id: 221, category: "강사 브랜드 페이지/프로필", subFeature: "프로필 편집(마이페이지)", item: "InstructorProfileEditCard에서 전문 분야/언어 태그 추가/삭제 저장", priority: "중" },
  { id: 222, category: "강사 브랜드 페이지/프로필", subFeature: "프로필 편집(마이페이지)", item: "SNS 링크 입력 필드 저장 및 취소(편집 중 이탈 시 원복) 동작", priority: "중" },
  { id: 223, category: "강사 브랜드 페이지/프로필", subFeature: "프로필 편집(마이페이지)", item: "교육 철학/좋아하는 다이빙 편집 후 실시간 반영 여부", priority: "중" },
  { id: 224, category: "강사 브랜드 페이지/프로필", subFeature: "프로필 편집(마이페이지)", item: "강사 자격증 서류 재업로드 시 기존 서류 대체 처리", priority: "중" },
  { id: 225, category: "강사 브랜드 페이지/프로필", subFeature: "프로필 편집(마이페이지)", item: "필수 항목 미입력 시 저장 버튼 비활성화 또는 에러 표시", priority: "중" },
  { id: 226, category: "강사 브랜드 페이지/프로필", subFeature: "프로필 편집(마이페이지)", item: "저장 성공/실패 토스트 메시지 정확성", priority: "중" },
  { id: 227, category: "강사 대시보드/정산", subFeature: "대시보드", item: "InstructorDashboard 요약 카드(예약수/매출/평점 등) 수치 정확성", priority: "상" },
  { id: 228, category: "강사 대시보드/정산", subFeature: "대시보드", item: "중복되던 마이페이지 탭이 제거되고 하단 네비게이션 마이페이지만 남았는지", priority: "중" },
  { id: 229, category: "강사 대시보드/정산", subFeature: "대시보드", item: "탭 구조(grid-cols-4)가 레이아웃 깨짐 없이 정상 표시되는지", priority: "중" },
  { id: 230, category: "강사 대시보드/정산", subFeature: "리뷰 관리", item: "InstructorReviewsPanel에서 본인 투어 후기 목록 필터/정렬", priority: "중" },
  { id: 231, category: "강사 대시보드/정산", subFeature: "리뷰 관리", item: "후기에 대한 강사 답글 기능(있을 경우) 동작", priority: "하" },
  { id: 232, category: "강사 대시보드/정산", subFeature: "채팅", item: "InstructorChatPanel에서 다이버와의 대화 목록/읽음 상태 표시", priority: "중" },
  { id: 233, category: "강사 대시보드/정산", subFeature: "채팅", item: "새 메시지 수신 시 알림 배지 갱신", priority: "중" },
  { id: 234, category: "강사 대시보드/정산", subFeature: "알림센터", item: "InstructorNotificationCenter에서 예약/취소/후기 등 이벤트별 알림 분류", priority: "중" },
  { id: 235, category: "강사 대시보드/정산", subFeature: "알림센터", item: "알림 읽음 처리 및 안읽음 개수 배지 정확성", priority: "중" },
  { id: 236, category: "강사 대시보드/정산", subFeature: "알림센터", item: "PushNotificationToggle 켬/끔 설정이 실제 푸시 수신 여부에 반영되는지", priority: "중" },
  { id: 237, category: "강사 대시보드/정산", subFeature: "정산/보증금", item: "정산 내역 다운로드(엑셀/PDF 등) 기능 동작", priority: "하" },
  { id: 238, category: "강사 대시보드/정산", subFeature: "정산/보증금", item: "정산 상세에서 세금/수수료 항목이 명확히 구분 표시되는지", priority: "중" },
  { id: 239, category: "강사 대시보드/정산", subFeature: "정산/보증금", item: "정산 지연/보류 상태 표시 및 사유 안내", priority: "중" },
  { id: 240, category: "강사 대시보드/정산", subFeature: "지원서/승인", item: "InstructorApplicationQueue(관리자)에서 신규 강사 승인/반려 처리", priority: "상" },
  { id: 241, category: "강사 대시보드/정산", subFeature: "지원서/승인", item: "반려 시 반려 사유가 지원자에게 전달되는지", priority: "상" },
  { id: 242, category: "강사 대시보드/정산", subFeature: "지원서/승인", item: "승인 후 강사 권한이 즉시(재로그인 없이) 반영되는지", priority: "상" },
  { id: 243, category: "강사 대시보드/정산", subFeature: "센터 관리", item: "CenterFormSection에서 강사 소속/제휴 센터 등록 및 관리자 승인 플로우", priority: "중" },
  { id: 244, category: "강사 대시보드/정산", subFeature: "센터 관리", item: "미승인 센터를 투어에 연결 시도할 때 차단 여부", priority: "중" },
  { id: 245, category: "강사 대시보드/정산", subFeature: "센터 관리", item: "승인된 센터 정보 수정 시 관련 투어에도 반영되는지", priority: "중" },
  { id: 246, category: "강사 대시보드/정산", subFeature: "최소인원 결정", item: "UnderMinDecisionPanel에서 진행/취소 결정 시 데이터가 즉시 DB에 반영되는지(과거 미반영 버그 회귀 테스트)", priority: "상" },
  { id: 247, category: "강사 대시보드/정산", subFeature: "최소인원 결정", item: "결정 이후 재변경이 가능한지, 가능하다면 이력 관리가 되는지", priority: "상" },
  { id: 248, category: "채팅/고객지원", subFeature: "1:1 채팅", item: "ChatList에서 대화방 목록 최신순 정렬 및 안읽음 표시", priority: "중" },
  { id: 249, category: "채팅/고객지원", subFeature: "1:1 채팅", item: "ChatRoom에서 메시지 송수신 실시간 반영 여부", priority: "중" },
  { id: 250, category: "채팅/고객지원", subFeature: "1:1 채팅", item: "이미지/파일 첨부 전송 기능 동작", priority: "중" },
  { id: 251, category: "채팅/고객지원", subFeature: "1:1 채팅", item: "차단/신고 기능(있을 경우) 동작", priority: "중" },
  { id: 252, category: "채팅/고객지원", subFeature: "1:1 채팅", item: "채팅 내용 검색 기능(있을 경우) 동작", priority: "중" },
  { id: 253, category: "채팅/고객지원", subFeature: "고객센터", item: "SupportChat에서 문의 접수 및 담당자 배정 플로우", priority: "중" },
  { id: 254, category: "채팅/고객지원", subFeature: "고객센터", item: "1:1 문의 내역이 마이페이지 '내 문의 보기'에서 정확히 조회되는지", priority: "중" },
  { id: 255, category: "채팅/고객지원", subFeature: "고객센터", item: "문의 답변 완료 시 알림이 정상 발송되는지", priority: "중" },
  { id: 256, category: "채팅/고객지원", subFeature: "고객센터", item: "AdminSupportPage/SupportTicketQueue에서 문의 상태(대기/처리중/완료) 변경 동작", priority: "중" },
  { id: 257, category: "채팅/고객지원", subFeature: "신고", item: "UserReportQueue에서 사용자 신고 접수/처리 플로우", priority: "하" },
  { id: 258, category: "채팅/고객지원", subFeature: "신고", item: "신고 누적에 따른 계정 제재 연동 여부", priority: "하" },
  { id: 259, category: "채팅/고객지원", subFeature: "매뉴얼/공지", item: "AdminNoticesPage에서 등록한 공지사항이 사용자 화면에 노출되는지", priority: "하" },
  { id: 260, category: "채팅/고객지원", subFeature: "매뉴얼/공지", item: "공지사항 노출 기간(시작/종료일) 설정이 정확히 반영되는지", priority: "하" },
  { id: 261, category: "채팅/고객지원", subFeature: "매뉴얼/공지", item: "AdminManualPage 운영 매뉴얼 내용 조회 권한(관리자 전용) 확인", priority: "하" },
  { id: 262, category: "알림", subFeature: "일반", item: "예약 확정/취소/환불 완료 등 주요 이벤트별 알림 발송 여부", priority: "상" },
  { id: 263, category: "알림", subFeature: "일반", item: "알림 클릭 시 관련 화면(예약 상세 등)으로 정확히 이동하는지", priority: "중" },
  { id: 264, category: "알림", subFeature: "일반", item: "알림 읽음/안읽음 상태 관리 정확성", priority: "중" },
  { id: 265, category: "알림", subFeature: "일반", item: "알림 설정 끔 상태에서 해당 유형 알림이 발송되지 않는지", priority: "중" },
  { id: 266, category: "알림", subFeature: "관리자", item: "AdminNotificationsPage에서 시스템 알림/이상 징후 알림이 정확히 노출되는지", priority: "중" },
  { id: 267, category: "알림", subFeature: "관리자", item: "관리자 알림이 실시간(폴링/구독)으로 갱신되는지", priority: "중" },
  { id: 268, category: "알림", subFeature: "푸시", item: "브라우저 푸시 권한 요청 플로우(허용/거부) 정상 동작", priority: "하" },
  { id: 269, category: "알림", subFeature: "푸시", item: "PWA 환경(sw.js)에서 백그라운드 푸시 수신 확인", priority: "하" },
  { id: 270, category: "마이페이지", subFeature: "다이버 마이페이지", item: "DiverMyPageView에서 예약내역/찜목록/문의내역 탭 전환 동작", priority: "중" },
  { id: 271, category: "마이페이지", subFeature: "다이버 마이페이지", item: "DiverSafetyProfileCard에 자격증/의료정보 등이 정확히 표시되는지", priority: "중" },
  { id: 272, category: "마이페이지", subFeature: "다이버 마이페이지", item: "LicenseVaultCard에서 자격증 서류 업로드/조회/삭제", priority: "중" },
  { id: 273, category: "마이페이지", subFeature: "다이버 마이페이지", item: "AccountActions(비밀번호 변경/계정 탈퇴 등) 기능 동작", priority: "중" },
  { id: 274, category: "마이페이지", subFeature: "계정 탈퇴", item: "계정 탈퇴 시 확인 절차(비밀번호 재입력 등) 존재 여부", priority: "상" },
  { id: 275, category: "마이페이지", subFeature: "계정 탈퇴", item: "탈퇴 후 개인정보 처리 방침에 따른 데이터 보관/삭제 정책 준수 확인", priority: "상" },
  { id: 276, category: "마이페이지", subFeature: "계정 탈퇴", item: "탈퇴 후 동일 이메일로 재가입 가능 여부 정책 확인", priority: "상" },
  { id: 277, category: "마이페이지", subFeature: "문의", item: "InquiryDialog에서 문의 작성 및 InquiryHistoryList 목록 반영", priority: "중" },
  { id: 278, category: "마이페이지", subFeature: "문의", item: "문의 답변 완료 상태 표시 정확성", priority: "중" },
  { id: 279, category: "마이페이지", subFeature: "관리자 마이페이지", item: "AdminMyPageView에서 관리자 계정 정보/권한 표시 확인", priority: "하" },
  { id: 280, category: "마이페이지", subFeature: "공통 UI", item: "다이버/강사/관리자 역할별로 마이페이지 구성 요소가 올바르게 분기되는지", priority: "하" },
  { id: 281, category: "마이페이지", subFeature: "공통 UI", item: "프로필 사진 변경 기능 동작", priority: "하" },
  { id: 282, category: "마이페이지", subFeature: "공통 UI", item: "언어/알림 등 개인 설정 저장 및 재접속 시 유지 확인", priority: "하" },
  { id: 283, category: "분쟁조정/안전", subFeature: "신고/조정 접수", item: "다이버가 강사를 신고하는 플로우와 강사가 다이버를 신고하는 플로우 모두 정상 동작", priority: "상" },
  { id: 284, category: "분쟁조정/안전", subFeature: "신고/조정 접수", item: "신고 접수 시 관련 예약/대화 내역이 자동 첨부되는지", priority: "상" },
  { id: 285, category: "분쟁조정/안전", subFeature: "신고/조정 접수", item: "증빙 자료(사진/파일) 첨부 기능 동작", priority: "상" },
  { id: 286, category: "분쟁조정/안전", subFeature: "조정 처리", item: "AdminArbitrationRoom에서 관리자가 양측 증빙을 확인하고 판정하는 플로우", priority: "상" },
  { id: 287, category: "분쟁조정/안전", subFeature: "조정 처리", item: "조정 결과에 따라 환불/패널티가 자동 또는 수동으로 연동되는지", priority: "중" },
  { id: 288, category: "분쟁조정/안전", subFeature: "조정 처리", item: "조정 진행 상태(접수/검토중/완료)가 양측에 동일하게 보이는지", priority: "중" },
  { id: 289, category: "분쟁조정/안전", subFeature: "패널티 부여", item: "PenaltyWarningPanel에서 경고 부여 시 사유 입력이 필수인지", priority: "상" },
  { id: 290, category: "분쟁조정/안전", subFeature: "패널티 부여", item: "패널티 부여 이력이 관리자 화면에서 누적 조회 가능한지", priority: "중" },
  { id: 291, category: "분쟁조정/안전", subFeature: "패널티 부여", item: "패널티 취소/정정 기능(오적용 시) 존재 여부", priority: "중" },
  { id: 292, category: "분쟁조정/안전", subFeature: "안전 규정 노출", item: "투어 상세 하단 '주요 정책 및 안전 규정' 문서가 항상 최신 버전으로 노출되는지", priority: "하" },
  { id: 293, category: "분쟁조정/안전", subFeature: "안전 규정 노출", item: "다이버/강사 위반 사항 및 제재 정책 페이지 링크 정상 동작", priority: "하" },
  { id: 294, category: "관리자 기능", subFeature: "대시보드", item: "KpiCardGrid의 핵심 지표(예약수/매출/신규가입 등) 정확성", priority: "상" },
  { id: 295, category: "관리자 기능", subFeature: "대시보드", item: "RevenueLineChart 기간별 매출 그래프 데이터 정확성", priority: "상" },
  { id: 296, category: "관리자 기능", subFeature: "대시보드", item: "BookingStatusDonut 예약 상태 비율 계산 정확성", priority: "상" },
  { id: 297, category: "관리자 기능", subFeature: "대시보드", item: "CountryBookingBarChart 국가별 예약 통계 정확성", priority: "상" },
  { id: 298, category: "관리자 기능", subFeature: "대시보드", item: "SystemStatusGrid 시스템 상태 표시(정상/장애) 정확성", priority: "상" },
  { id: 299, category: "관리자 기능", subFeature: "대시보드", item: "RecentActivityFeed 최근 활동 로그 실시간 갱신", priority: "상" },
  { id: 300, category: "관리자 기능", subFeature: "대시보드", item: "RecentBookingsTable 최근 예약 목록 최신순 정렬", priority: "상" },
  { id: 301, category: "관리자 기능", subFeature: "대시보드", item: "RecentReportsPanel 최근 신고 목록 표시", priority: "상" },
  { id: 302, category: "관리자 기능", subFeature: "대시보드", item: "OperationalHighlightsPanel 운영 하이라이트 지표 정확성", priority: "상" },
  { id: 303, category: "관리자 기능", subFeature: "대시보드", item: "PendingInquiriesPanel 미처리 문의 카운트 정확성", priority: "상" },
  { id: 304, category: "관리자 기능", subFeature: "대시보드", item: "PenaltyWarningPanel 대시보드 위젯과 실제 패널티 데이터 일치", priority: "상" },
  { id: 305, category: "관리자 기능", subFeature: "대시보드", item: "CenterApprovalPanel 승인 대기 센터 목록 정확성", priority: "상" },
  { id: 306, category: "관리자 기능", subFeature: "대시보드", item: "InstructorVerificationPanel 강사 인증 대기 목록 정확성", priority: "상" },
  { id: 307, category: "관리자 기능", subFeature: "사용자 관리", item: "AdminUsersPage에서 사용자 검색/필터(역할, 상태 등) 동작", priority: "상" },
  { id: 308, category: "관리자 기능", subFeature: "사용자 관리", item: "AdminUserDetailPage에서 특정 사용자 상세 정보 및 활동 이력 조회", priority: "상" },
  { id: 309, category: "관리자 기능", subFeature: "사용자 관리", item: "사용자 계정 정지/해제 처리 및 즉시 반영 여부", priority: "상" },
  { id: 310, category: "관리자 기능", subFeature: "사용자 관리", item: "사용자 역할 변경(다이버→강사 등) 처리", priority: "상" },
  { id: 311, category: "관리자 기능", subFeature: "사용자 관리", item: "사용자 삭제 시 연관 데이터(예약/후기 등) 처리 정책 확인", priority: "상" },
  { id: 312, category: "관리자 기능", subFeature: "강사 관리", item: "AdminInstructorsPage에서 강사 목록 필터(인증 상태/패널티 유무) 동작", priority: "상" },
  { id: 313, category: "관리자 기능", subFeature: "강사 관리", item: "강사 상세에서 경고 부여 시 사유 입력 필드가 정상 작동하는지", priority: "상" },
  { id: 314, category: "관리자 기능", subFeature: "강사 관리", item: "강사 인증 배지 부여/회수 처리", priority: "상" },
  { id: 315, category: "관리자 기능", subFeature: "강사 관리", item: "강사 정산 계좌 정보 관리 및 검증", priority: "상" },
  { id: 316, category: "관리자 기능", subFeature: "강사 관리", item: "강사 활동 정지 처리 시 진행 중인 투어에 미치는 영향 확인", priority: "상" },
  { id: 317, category: "관리자 기능", subFeature: "투어 관리", item: "AdminToursPage에서 전체 투어 목록 상태별 필터링", priority: "중" },
  { id: 318, category: "관리자 기능", subFeature: "투어 관리", item: "신규 등록 투어 승인/반려 처리 플로우", priority: "중" },
  { id: 319, category: "관리자 기능", subFeature: "투어 관리", item: "반려 사유가 강사에게 정확히 전달되는지", priority: "중" },
  { id: 320, category: "관리자 기능", subFeature: "투어 관리", item: "투어 강제 마감/취소 처리 시 예약자 환불 프로세스 연동", priority: "중" },
  { id: 321, category: "관리자 기능", subFeature: "투어 관리", item: "투어 노출 순서(추천/광고 등) 관리 기능", priority: "중" },
  { id: 322, category: "관리자 기능", subFeature: "예약 관리", item: "AdminBookingsPage에서 예약 검색(예약자/투어명/기간) 동작", priority: "중" },
  { id: 323, category: "관리자 기능", subFeature: "예약 관리", item: "예약 상태 수동 변경(관리자 개입) 기능 및 이력 기록", priority: "중" },
  { id: 324, category: "관리자 기능", subFeature: "예약 관리", item: "이중예약/오류예약 발견 시 수정 처리 플로우", priority: "중" },
  { id: 325, category: "관리자 기능", subFeature: "센터 관리", item: "AdminCentersPage에서 센터 등록 승인/반려 처리", priority: "중" },
  { id: 326, category: "관리자 기능", subFeature: "센터 관리", item: "센터 정보 수정 이력 관리", priority: "중" },
  { id: 327, category: "관리자 기능", subFeature: "센터 관리", item: "센터별 연결된 투어/강사 목록 조회", priority: "중" },
  { id: 328, category: "관리자 기능", subFeature: "쿠폰/프로모션", item: "AdminCouponsPage에서 쿠폰 생성 시 할인율/금액, 유효기간 검증", priority: "중" },
  { id: 329, category: "관리자 기능", subFeature: "쿠폰/프로모션", item: "쿠폰 발급 대상(전체/특정 그룹) 필터링 정확성", priority: "중" },
  { id: 330, category: "관리자 기능", subFeature: "쿠폰/프로모션", item: "쿠폰 사용 현황(발급수/사용수) 통계 정확성", priority: "중" },
  { id: 331, category: "관리자 기능", subFeature: "쿠폰/프로모션", item: "쿠폰 비활성화 시 즉시 결제 화면에서 적용 불가로 반영되는지", priority: "중" },
  { id: 332, category: "관리자 기능", subFeature: "정산/정산관리", item: "PayoutManagement/AdminPayoutsPage에서 강사별 정산 대상 목록 정확성", priority: "상" },
  { id: 333, category: "관리자 기능", subFeature: "정산/정산관리", item: "정산 승인 처리 후 강사 SettlementLedger에 반영되는지", priority: "상" },
  { id: 334, category: "관리자 기능", subFeature: "정산/정산관리", item: "정산 보류/거부 처리 및 사유 기록", priority: "상" },
  { id: 335, category: "관리자 기능", subFeature: "정산/정산관리", item: "세금계산서 발행 대상 필터링 정확성", priority: "상" },
  { id: 336, category: "관리자 기능", subFeature: "리포트/신고", item: "ReportsLog/AdminReportsPage에서 전체 신고 이력 조회 및 상태 필터", priority: "중" },
  { id: 337, category: "관리자 기능", subFeature: "리포트/신고", item: "UserReportQueue에서 신고 처리(경고/정지/기각) 액션 동작", priority: "중" },
  { id: 338, category: "관리자 기능", subFeature: "리포트/신고", item: "반복 신고 대상 사용자 하이라이트 표시(있을 경우)", priority: "중" },
  { id: 339, category: "관리자 기능", subFeature: "후기 모니터링", item: "ReviewModerationQueue에서 신고된 후기 승인/삭제 처리", priority: "중" },
  { id: 340, category: "관리자 기능", subFeature: "후기 모니터링", item: "삭제된 후기가 실시간으로 사용자 화면에서 사라지는지", priority: "중" },
  { id: 341, category: "관리자 기능", subFeature: "고객지원", item: "AdminSupportPage/SupportTicketQueue에서 문의 배정 및 답변 처리", priority: "중" },
  { id: 342, category: "관리자 기능", subFeature: "고객지원", item: "문의 우선순위(긴급/일반) 분류 및 정렬", priority: "중" },
  { id: 343, category: "관리자 기능", subFeature: "고객지원", item: "답변 완료 후 사용자에게 알림 발송 여부", priority: "중" },
  { id: 344, category: "관리자 기능", subFeature: "공지/알림", item: "AdminNoticesPage에서 공지 등록/수정/삭제 및 게시 기간 관리", priority: "중" },
  { id: 345, category: "관리자 기능", subFeature: "공지/알림", item: "AdminNotificationsPage에서 전체 발송 알림(공지성 푸시 등) 이력 조회", priority: "중" },
  { id: 346, category: "관리자 기능", subFeature: "공지/알림", item: "타겟팅 알림(특정 역할/지역 대상) 발송 정확성", priority: "중" },
  { id: 347, category: "관리자 기능", subFeature: "활동 로그", item: "AdminActivityPage에서 관리자별 작업 이력(감사 로그) 기록 정확성", priority: "상" },
  { id: 348, category: "관리자 기능", subFeature: "활동 로그", item: "중요 작업(계정 정지, 강제 취소 등)에 대한 로그 누락 여부 점검", priority: "상" },
  { id: 349, category: "관리자 기능", subFeature: "분석", item: "AdminAnalyticsPage에서 기간별 지표(가입자/매출/재방문율) 계산 정확성", priority: "하" },
  { id: 350, category: "관리자 기능", subFeature: "분석", item: "필터(기간, 지역, 카테고리) 변경 시 그래프/표가 즉시 갱신되는지", priority: "하" },
  { id: 351, category: "관리자 기능", subFeature: "분석", item: "CSV/엑셀 내보내기 기능(있을 경우) 데이터 정합성", priority: "하" },
  { id: 352, category: "관리자 기능", subFeature: "설정", item: "AdminSettingsPage에서 플랫폼 수수료율 등 정책값 변경 시 즉시 반영 범위 확인", priority: "상" },
  { id: 353, category: "관리자 기능", subFeature: "설정", item: "설정 변경 권한이 최고관리자 등 제한된 역할에만 있는지", priority: "상" },
  { id: 354, category: "관리자 기능", subFeature: "설정", item: "설정 변경 이력이 기록되는지", priority: "상" },
  { id: 355, category: "관리자 기능", subFeature: "매뉴얼/기타", item: "AdminManualPage 운영 매뉴얼 최신 버전 유지 여부", priority: "하" },
  { id: 356, category: "관리자 기능", subFeature: "매뉴얼/기타", item: "AdminMorePage 추가 메뉴 항목 접근 권한 확인", priority: "하" },
  { id: 357, category: "관리자 기능", subFeature: "매뉴얼/기타", item: "AdminHomePage 관리자 홈 화면의 요약 정보와 상세 페이지 데이터 일치", priority: "하" },
  { id: 358, category: "관리자 기능", subFeature: "레이아웃/권한", item: "AdminLayout/AdminSidebar 메뉴 구조가 실제 라우트와 1:1 매핑되는지", priority: "중" },
  { id: 359, category: "관리자 기능", subFeature: "레이아웃/권한", item: "권한 없는 관리자 하위 역할(있을 경우) 접근 제한 확인", priority: "하" },
  { id: 360, category: "관리자 기능", subFeature: "레이아웃/권한", item: "모바일 해상도에서 관리자 화면 레이아웃 깨짐 여부", priority: "하" },
  { id: 361, category: "게임/포인트", subFeature: "플레이", item: "GamePlay 진입 및 포인트 획득 로직 정확성", priority: "중" },
  { id: 362, category: "게임/포인트", subFeature: "플레이", item: "GamePlayerContext의 포인트/상태가 새로고침 후에도 유지되는지", priority: "중" },
  { id: 363, category: "게임/포인트", subFeature: "플레이", item: "포인트 획득 이벤트가 실제 다이빙 활동(투어 완료 등)과 연동되는지", priority: "중" },
  { id: 364, category: "게임/포인트", subFeature: "리더보드", item: "GameLeaderboard 순위 계산이 실제 포인트 데이터와 일치하는지", priority: "중" },
  { id: 365, category: "게임/포인트", subFeature: "리더보드", item: "동점자 처리 규칙(있을 경우) 확인", priority: "하" },
  { id: 366, category: "게임/포인트", subFeature: "리더보드", item: "리더보드 갱신 주기 및 실시간성 확인", priority: "하" },
  { id: 367, category: "게임/포인트", subFeature: "상점", item: "GameShop에서 포인트로 아이템/혜택 교환 시 포인트 차감이 정확한지", priority: "상" },
  { id: 368, category: "게임/포인트", subFeature: "상점", item: "잔여 포인트 부족 시 구매 버튼 비활성화", priority: "상" },
  { id: 369, category: "게임/포인트", subFeature: "상점", item: "교환한 혜택이 실제 예약/결제에 정상 적용되는지", priority: "상" },
  { id: 370, category: "게임/포인트", subFeature: "공통", item: "게임 기능이 메인 서비스(예약/결제) 플로우를 방해하지 않는지", priority: "중" },
  { id: 371, category: "게임/포인트", subFeature: "공통", item: "게임 관련 오류가 메인 앱 크래시로 이어지지 않는지(에러 바운더리)", priority: "중" },
  { id: 372, category: "공통 품질", subFeature: "반응형", item: "모바일(360~430px), 태블릿, 데스크톱 해상도별 레이아웃 깨짐 여부", priority: "상" },
  { id: 373, category: "공통 품질", subFeature: "반응형", item: "하단 네비게이션이 모바일에서 항상 접근 가능한지", priority: "중" },
  { id: 374, category: "공통 품질", subFeature: "반응형", item: "긴 텍스트(강사명, 투어명 등)의 줄바꿈/말줄임 처리", priority: "중" },
  { id: 375, category: "공통 품질", subFeature: "성능", item: "이미지 다수 업로드/갤러리 페이지 로딩 속도", priority: "중" },
  { id: 376, category: "공통 품질", subFeature: "성능", item: "번들 크기(현재 2MB 이상 청크 경고) 개선 여부 - 코드 스플리팅 검토", priority: "하" },
  { id: 377, category: "공통 품질", subFeature: "성능", item: "초기 스플래시 화면 노출 시간이 과도하게 길지 않은지", priority: "하" },
  { id: 378, category: "공통 품질", subFeature: "보안", item: "Supabase RLS(행 수준 보안) 정책이 역할별 데이터 접근을 올바르게 제한하는지", priority: "상" },
  { id: 379, category: "공통 품질", subFeature: "보안", item: "타인의 예약/결제/개인정보에 API 직접 호출로 접근 가능한지 점검", priority: "상" },
  { id: 380, category: "공통 품질", subFeature: "보안", item: "관리자 전용 API가 프론트엔드 라우트 가드뿐 아니라 서버측에서도 차단되는지", priority: "상" },
  { id: 381, category: "공통 품질", subFeature: "보안", item: "파일 업로드 경로에 대한 파일 타입/크기 서버측 검증 여부", priority: "상" },
  { id: 382, category: "공통 품질", subFeature: "브랜딩/메타", item: "브라우저 탭 제목/공유 미리보기(og:meta)가 ALL BLUE 브랜딩으로 정확히 노출되는지", priority: "중" },
  { id: 383, category: "공통 품질", subFeature: "브랜딩/메타", item: "파비콘이 ALL BLUE 로고로 정상 표시되는지", priority: "하" },
  { id: 384, category: "공통 품질", subFeature: "다국어", item: "i18next 기반 언어 전환(한국어/영어 등) 시 주요 화면 번역 누락 여부", priority: "하" },
  { id: 385, category: "공통 품질", subFeature: "다국어", item: "언어 전환 후에도 숫자/날짜 형식이 지역에 맞게 표시되는지", priority: "하" },
];

export const QA_CHECKLIST_CATEGORIES: string[] = Array.from(
  new Set(QA_CHECKLIST_ITEMS.map((i) => i.category)),
);

export const QA_CHECKLIST_STATUS_OPTIONS = ["미확인", "Pass", "Fail", "N/A", "진행중"] as const;
export type QaChecklistStatus = (typeof QA_CHECKLIST_STATUS_OPTIONS)[number];

